"use client";

import type { Config } from "@puckeditor/core";
import { EventCard, NewsOverlayCard } from "./components/cards";
import {
  LatestNewsAuto,
  NewsListPaginated,
  UpcomingEventsAuto,
} from "./components/news-feed";
import {
  ContactInfo,
  DepartmentCard,
  Heading,
  IconText,
  ImageTextBlock,
  NewsCard,
  ProfileCard,
  SectionHeader,
  TextBlock,
} from "./components/content";
import { HeroFullScreen, StatsCounter } from "./components/hero";
import {
  AnnouncementBar,
  Banner,
  ButtonBlock,
  PersonaSelector,
  SearchOverlay,
  SubscribeBanner,
  TagNotificationBar,
} from "./components/interactive";
import {
  Card,
  Columns,
  Container,
  Divider,
  FooterBlock,
  Grid,
  Spacer,
} from "./components/layout";
import {
  ImageBlock,
  ImageGallery,
  ImageSlider,
  LogoGrid,
  LogoSlider,
  MapEmbed,
  PartnerShowcase,
  VideoEmbed,
} from "./components/media";
import {
  LanguageSwitcher,
  Navbar,
  NavLinks,
  QuickLinks,
  SocialIcons,
} from "./components/navigation";
import {
  PostBody,
  PostCoverImage,
  PostEventInfo,
  PostHeader,
  PostReaderTools,
  PostTagList,
  PostTitle,
} from "./components/post-placeholders";

export const puckConfig: Config = {
  categories: {
    layout: {
      title: "Layout",
      components: [
        "Container",
        "Columns",
        "Grid",
        "Card",
        "FooterBlock",
        "Spacer",
        "Divider",
      ],
    },
    navigation: {
      title: "Navigation",
      components: [
        "Navbar",
        "NavLinks",
        "QuickLinks",
        "SocialIcons",
        "LanguageSwitcher",
      ],
    },
    content: {
      title: "Content",
      components: [
        "SectionHeader",
        "NewsCard",
        "ProfileCard",
        "DepartmentCard",
        "Heading",
        "TextBlock",
        "IconText",
        "ContactInfo",
        "ImageTextBlock",
      ],
    },
    media: {
      title: "Media",
      components: [
        "ImageSlider",
        "ImageBlock",
        "ImageGallery",
        "LogoGrid",
        "LogoSlider",
        "PartnerShowcase",
        "VideoEmbed",
        "MapEmbed",
      ],
    },
    interactive: {
      title: "Interactive",
      components: [
        "ButtonBlock",
        "Banner",
        "AnnouncementBar",
        "SearchOverlay",
        "PersonaSelector",
        "SubscribeBanner",
        "TagNotificationBar",
      ],
    },
    hero: {
      title: "Hero & Stats",
      components: ["HeroFullScreen", "StatsCounter"],
    },
    cards: {
      title: "Cards",
      components: [
        "NewsOverlayCard",
        "EventCard",
        "LatestNewsAuto",
        "UpcomingEventsAuto",
        "NewsListPaginated",
      ],
    },
    post: {
      title: "Post Placeholders",
      components: [
        "PostHeader",
        "PostTitle",
        "PostCoverImage",
        "PostTagList",
        "PostBody",
        "PostEventInfo",
        "PostReaderTools",
      ],
    },
  },
  components: {
    Heading,
    TextBlock,
    ImageBlock,
    ButtonBlock,
    Spacer,
    Divider,
    Card,
    IconText,
    Banner,
    NavLinks,
    Columns,
    Container,
    Grid,
    ImageGallery,
    VideoEmbed,
    MapEmbed,
    ImageSlider,
    SectionHeader,
    NewsCard,
    ProfileCard,
    LogoGrid,
    LogoSlider,
    FooterBlock,
    SocialIcons,
    ContactInfo,
    AnnouncementBar,
    Navbar,
    QuickLinks,
    LanguageSwitcher,
    DepartmentCard,
    SearchOverlay,
    HeroFullScreen,
    StatsCounter,
    NewsOverlayCard,
    EventCard,
    PersonaSelector,
    ImageTextBlock,
    LatestNewsAuto,
    UpcomingEventsAuto,
    NewsListPaginated,
    PartnerShowcase,
    SubscribeBanner,
    TagNotificationBar,
    PostTitle,
    PostBody,
    PostCoverImage,
    PostTagList,
    PostEventInfo,
    PostHeader,
    PostReaderTools,
  } as any,
};
