"use client";

import {
  ArrowDown,
  ArrowRight,
  Bell,
  BellRing,
  Building2,
  Calendar,
  CalendarPlus,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Columns3,
  Copy,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Folder,
  GalleryHorizontalEnd,
  Globe,
  GraduationCap,
  GripVertical,
  Handshake,
  Hash,
  HelpCircle,
  History,
  Image as LucideImage,
  Images,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  Link as LinkIconLucide,
  Link2Off,
  List,
  ListVideo,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  Minus,
  MoreVertical,
  MousePointer2,
  MoveVertical,
  Newspaper,
  Palette,
  PanelBottom,
  Pencil,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Puzzle,
  Search,
  Settings,
  Space,
  Trash2,
  Type,
  Upload,
  UploadCloud,
  User,
  Users,
  X,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

/**
 * Translates Material Symbols Outlined glyph names (stored in DB and frontend
 * config) to lucide-react components. Keeps the existing `Widget.icon` column
 * schema unchanged — strings stay as Material names and resolve here.
 */
export const IconMap: Record<string, LucideIcon> = {
  apartment: Building2,
  add: Plus,
  add_circle: PlusCircle,
  add_circle_outline: PlusCircle,
  arrow_drop_down: ChevronDown,
  arrow_forward: ArrowRight,
  article: FileText,
  bottom_navigation: PanelBottom,
  building: Building2,
  calendar_add_on: CalendarPlus,
  calendar_month: Calendar,
  campaign: Megaphone,
  category: LayoutGrid,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: UploadCloud,
  content_copy: Copy,
  copy: Copy,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutPanelLeft,
  delete: Trash2,
  drag_handle: GripVertical,
  drag_indicator: GripVertical,
  duplicate: Copy,
  edit: Pencil,
  email: Mail,
  event: Calendar,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  extension_off: Puzzle,
  featured_play_list: ListVideo,
  folder: Folder,
  folder_open: Folder,
  group: Users,
  groups: Users,
  handshake: Handshake,
  height: MoveVertical,
  help: HelpCircle,
  history: History,
  horizontal_rule: Minus,
  image: LucideImage,
  info: Info,
  keyboard_arrow_down: ChevronDown,
  language: Globe,
  link: LinkIconLucide,
  link_off: Link2Off,
  local_fire_department: Flame,
  local_library: GraduationCap,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  map: Map,
  memory: Hash,
  menu: Menu,
  more_vert: MoreVertical,
  newspaper: Newspaper,
  notifications: Bell,
  notifications_active: BellRing,
  number: Hash,
  open_in_new: ArrowRight,
  palette: Palette,
  person: User,
  photo_library: Images,
  play_arrow: Play,
  play_circle: PlayCircle,
  publish: Upload,
  redo: ArrowRight,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  settings: Settings,
  smart_button: MousePointer2,
  spacer: Space ?? MoveVertical,
  string: Type,
  support_agent: Users,
  title: Type,
  translate: Globe,
  undo: ArrowDown,
  unpublished: EyeOff,
  view_carousel: GalleryHorizontalEnd,
  view_column: Columns3,
  view_list: List,
  visibility: Eye,
  visibility_off: EyeOff,
  web: Globe,
  web_stories: FileText,
  widget_data: LayoutGrid,
  widgets: LayoutGrid,
};

export const DEFAULT_ICON: LucideIcon = LayoutGrid;

type DynamicIconProps = {
  name: string | null | undefined;
  className?: string;
  style?: React.CSSProperties;
  size?: number;
  fallback?: LucideIcon;
};

export function DynamicIcon({
  name,
  className,
  style,
  size,
  fallback,
}: DynamicIconProps) {
  const Icon = (name ? IconMap[name] : null) ?? fallback ?? DEFAULT_ICON;
  if (
    name &&
    !IconMap[name] &&
    typeof process !== "undefined" &&
    process.env.NODE_ENV !== "production"
  ) {
    console.warn(`[DynamicIcon] No lucide mapping for "${name}"`);
  }
  return <Icon className={className} style={style} size={size} />;
}

export {
  ArrowDown as ArrowDownIcon,
  ArrowRight as ArrowRightIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Copy as CopyIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  GripVertical as GripVerticalIcon,
  HelpCircle as HelpCircleIcon,
  LucideImage as ImageIcon,
  Info as InfoIcon,
  LayoutGrid as LayoutGridIcon,
  LinkIconLucide as LinkIcon,
  Link2Off as Link2OffIcon,
  LogOut as LogOutIcon,
  Menu as MenuIcon,
  MoreVertical as MoreVerticalIcon,
  Palette as PaletteIcon,
  Pencil as PencilIcon,
  Plus as PlusIcon,
  PlusCircle as PlusCircleIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Trash2 as TrashIcon,
  Upload as UploadIcon,
  UploadCloud as UploadCloudIcon,
  X as XIcon,
};
